### ISSUE TITLE
On-screen buttons covering app

### ISSUE THREAD

**Issue by Abbe98** [Biocaching/app#1]
Height is ignoring the on-screen system buttons, still scrollable.

![screenshot_2016-01-04-08-49-01](https://cloud.githubusercontent.com/assets/2631719/12232770/baaf73ee-b861-11e5-8529-b57dd8812442.png)

**Comment by pbb72** [comment]
In principle, Android apps are not adjusted to screen length, and scroll instead. But I've applied a quick-fix for this issue, all content should now also fit in your screen.

**Comment by Abbe98** [comment]
So for supporting even more screen sizes this would be something we has to consider in the general design.

**Comment by pbb72** [comment]
Yes. But normally Android app screens are so full of information, that it cannot be fitted onto a single screen, and content is simply scrolled like a normal webpage.

The only exception that I have been able to find, where content is fitted to the screen, is "empty" screens with just a placeholder image and/or text such as this screen:

![screenshot_2016-01-25-23-44-10](https://cloud.githubusercontent.com/assets/1436366/12567282/8ebad806-c3be-11e5-8bd4-6ff2cb5986e5.png)

If you find more examples of Android apps that have been designed to fit/fill the screen (apart from of course full-screen games), I would be happy to have a look at them!

By the way, a new version (0.3.3) with adjusted screen layout has now been pushed to the Market, tell me if the screen fits better now.

**Comment by Abbe98** [comment]
It fits now.

I think we should move the submit button to somewhere it's never hidden on any device in the future.

**Comment by pbb72** [comment]
I am going to use a "FAB" (Floating Action Button) for the submit: https://www.google.com/design/spec/components/buttons-floating-action-button.html
