### ISSUE TITLE
Alert - unexpected status 0

### ISSUE THREAD

**Issue by bjornhjelle** [Biocaching/app#2]
Tester appen, versjon 0.6.0 og får denne meldingen når jeg får via søk og navigerer i taksonomien.

**Comment by pbb72** [comment]
Bekreftet, dette skjer hovedsakelig når en ny forespørsel sendes til serveren før pågående er ferdig. Hører gjerne om dette også skjer hvis det brukes mer tid mellom hver forespørsel. (10 sekunder burde være nok for at alt er lastet ned.)

**Comment by bjornhjelle** [comment]
Det er mulig at det fungerer slik, men f eks når listen med et nivå i taksonomien kommer opp er det vel klart for å klikke for å sende ny forespørsel?
Hva skyldes dette?

**Comment by pbb72** [comment]
Ja, det burde funke fint. På hvilken listen får du feilmeldingen? Er det på topp-nivået i folkelige taxonomien?

**Comment by bjornhjelle** [comment]
På alle nivå i taksonomien så vidt jeg kan se, tror ikke jeg får det i den vitenskapelige

**Comment by pbb72** [comment]
Og du får det altså også når du venter til alle bildene er lastet ned?

**Comment by pbb72** [comment]
Jeg har publisert en ny versjon på Play butikken. Kan du sjekke om du får melding om status 0 når du har fått versjon 0.6.1?

**Comment by bjornhjelle** [comment]
Fungerer nå, får ikke denne feilen
