### ISSUE TITLE
show more species in taxonomy navigation 

### ISSUE THREAD

**Issue by bjornhjelle** [Biocaching/app#24]
When reaching species level in the taxonomy, it must be possible to load the next set of species with a link ("show more" or similar) or by automatically loading as you scroll.

**Comment by pbb72** [comment]
I don't really understand. As far as I know, the app currently displays all species inside the chosen genus. Are there species I am missing, or did you wish for a button to load the species for the next genus?

**Comment by bjornhjelle** [comment]
In the taxonomy, when you klikk "Dyr", then "Fugler", then "Ender og Gjess", only the first 10 birds in the category "Ender og gjess" are shown.
There should be a link to show the next 10, or it could automatically fetch the next 10 when you scroll to the bottom of the page.

**Comment by pbb72** [comment]
You're right, that's a bug in the popular taxonomy browser, it works correctly in the scientific taxonomy. I will correct that with next version.
