### ISSUE TITLE
gh-pages broken unless bower_components is checked in.

### ISSUE THREAD

**Issue by Abbe98** [Biocaching/app#29]
See http://biocaching.github.io/app/signin.html in any web browser.

**Comment by pbb72** [comment]
After installing Bower (`npm install -g bower`) you need to install the required Bower packages by running `bower install` from the directory. Does that help?

**Comment by Abbe98** [comment]
Sure, but currently we would need to check in the `bower_components`
directory to Github for the live biocaching.github.io/app to work...

2017-04-11 16:34 GMT+02:00 Peter <notifications@github.com>:

**Comment by pbb72** [comment]
Ah yes of course, that I forgot! :D Will fix that in the next release.
