### ISSUE TITLE
Link på kamera og 'folder'-icon byttet om?

### ISSUE THREAD

**Issue by bjornhjelle** [Biocaching/app#3]
På siden for å lage observasjon går linken på kamera-ikonet til galleriet.
Linken på folder-ikonet ser ut til å gå til kameraet, men det skjer ingenting når jeg klikker på den.

**Comment by pbb72** [comment]
Det stemmer, kameraet funker ikke bra i versjon 0.6.0 av Android-appen. Det funker bedre hvis du åpner web-appen på https://biocaching.github.io/app/ på mobiltelefon. Gallerie-knappen (folder-ikonet) er ikke aktiv på hverken Android- eller web-appen.

Kameraet vil funke bedre i versjon 0.6.1. Koden er allerede sjekket inn på 3d305a9.

**Comment by pbb72** [comment]
Kameraet lastes nå automatisk fra kamera-skjermen. Ikke optimalt enda, men man trenger ikke lenger å trykke på knapper.
