### ISSUE TITLE
species name seems to be shown in a random language

### ISSUE THREAD

**Issue by bjornhjelle** [Biocaching/app#30]
In the list of observations I now find: 
- spissmusfamilien
- European Robin
- Marsh Tit
- hvitveis
- blåveis
etc
So a mix of english and norwegian.
The front-end should use the users preferred language if available in the order they are set in the preferences. My user has languages set to: nob, eng

**Comment by pbb72** [comment]
That looks like a bug, the Norwegian names are available so they should be displayed.
